# see: https://github.com/toddsampson/ros-docker/blob/master/docker-compose.yml
# https://github.com/LI3DS/ros-li3ds/blob/master/docker-compose.yml
version: '2'
services:
  roscore:
    image: ros:kinetic
    container_name: roscore
    hostname: roscore
    ports:
      - 11311:11311
    command: roscore

  # works fine
  ig-server:
    image: cmu-mars/ig-server
    container_name: ig-server
    hostname: ig-server
    environment:
      - "ROS_HOSTNAME=ig-server"
      - "ROS_MASTER_URI=http://roscore:11311"
    depends_on:
      - roscore
    command: python src/ig_action_server/src/ig_server.py

  # rainbow should run inside its own container
  # TODO: doesn't work -- gets very angry that Gazebo isn't running
  brasscomms:
    image: cmu-mars/brasscomms
    container_name: brasscomms
    hostname: brasscomms
    environment:
      - "ROS_HOSTNAME=brasscomms"
      - "ROS_MASTER_URI=http://roscore:11311"
    depends_on:
      - roscore
      - ig-server
    command: python src/brasscomms/src/brasscomms.py

  # not working
  #  gazebo:
  #    image: cmu-mars/gazebo
  #    container_name: gazebo
  #    hostname: gazebo
  #    environment:
  #      - "ROS_HOSTNAME=gazebo"
  #      - "ROS_MASTER_URI=http://roscore:11311"
  #    depends_on:
  #      - roscore
  #      - ig-server
  #    command: roslaunch cp_gazebo cp1.launch
